title: [The title of your site]
author: [Your name]
description: [A short description of your site's purpose]

# Theme config
# docs: https://github.com/pages-themes/minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
